import type { Metadata } from "next";
import Header from "./components/Header";
import Aside from "./components/Aside";
import "./globals.css";
import { useState } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body >
        <Header/>
        <Aside/>
        {children}
        </body>
    </html>
  );
}
